name: Testing variable inb-out

on:
  push:
    branches: [ master ]

jobs:

  my-job:
     
    runs-on: windows-latest

    env:
      anyParam: 'any'
    
    steps:
      
      - uses: actions/checkout@v1
      - name: Run a one-line script that generates output
        run: powershell ./incrementVersion.ps1

      - name: Print out previously set env. variable
        run: powershell Write-Host $env:BUILDING_VERSION

      - name: Run a one-line script that grabs previous output
        run: powershell ./showVersion.ps1 -versionParameter $env:BUILDING_VERSION

      - name: Test to print out something
        run: powershell Write-Host ${{ secrets.NUGET_API_KEY }}


      - name: Commit
        run: git commit -m "$m"

      - name: Push
        run: git push origin master

      - name: Add version
        run: git tag -a $env:BUILDING_VERSION -m "new release"

      - name: Push
        run: git push origin $env:BUILDING_VERSION


      - name: Get latest tag
        run: git describe --tags `git rev-list --tags --max-count=1`

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
          WITH_V: true
          CUSTOM_TAG: $env:BUILDING_VERSION



          